server:
  port: 8084
spring:
  rabbitmq:
    host: 192.168.118.168
    virtual-host: /
  redis:
    host: 192.168.118.168
    password: root
dubbo:
  application:
    name: shop-web-sso
  registry:
    address: zookeeper://192.168.118.168:2181
  consumer:
    check: false
    timeout: 10000