server:
  port: 8083
dubbo:
  registry:
    address: zookeeper://192.168.118.168:2181
  application:
    name: shop-web-item
  consumer:
    check: false
spring:
  rabbitmq:
    host: 192.168.118.168
    virtual-host: /
