server:
  port: 8081
spring:
  thymeleaf:
    cache: false
dubbo:
  registry:
    address: zookeeper://192.168.118.168:2181
  application:
    name: front-web
  consumer:
    check: false
    timeout: 10000
