server:
  port: 8080

spring:
  thymeleaf:
    cache: false

upload:
  path: D:/DummyDir/

dubbo:
  application:
    name: shop-back-web
  registry:
    address: zookeeper://192.168.118.168:2181
  consumer:
    check: false
fdfs:
  so-timeout: 10000
  tracker-list:
    - 192.168.118.168:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
