server:
  port: 8085
spring:
  redis:
    host: 192.168.118.168
    password: root
dubbo:
  registry:
    address: zookeeper://192.168.118.168:2181
  application:
    name: shop-web-shopcart
  consumer:
    check: false
    timeout: 10000
