spring:
  datasource:
    url: jdbc:mysql:///shop1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  registry:
    address: zookeeper://192.168.118.168:2181
  application:
    name: user-service
  protocol:
    port: -1


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
