spring:
  orderdb1:
    datasource:
      url: jdbc:mysql:///shop1903_orderdb1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      keyword: orderdb1
  orderdb2:
    datasource:
      url: jdbc:mysql:///shop1903_orderdb2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      keyword: orderdb2

  redis:
    host: 192.168.118.168
    password: root

dubbo:
  registry:
    address: zookeeper://192.168.118.168:2181
  application:
    name: shop-order-service
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 10000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
